# Generated by Django 3.0.6 on 2020-05-22 12:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_restuarant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restuarant',
            new_name='Restaurant',
        ),
    ]
